apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: koagyu-com-tls
spec:
  secretName: koagyu-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: koagyu.com
  dnsNames:
    - koagyu.com
    - www.koagyu.com
